import re
from typing import List
import httpx
from ai.schemas import GitHubExportItem, GitHubExportResponse


def parse_repo_info(owner_input: str, repo_input: str):
    """사용자가 URL 전체를 입력했더라도 owner와 repo를 안전하게 추출"""
    combined = f"{owner_input.strip()}/{repo_input.strip()}".replace("https://github.com/", "")
    parts = [p for p in combined.split("/") if p]
    if len(parts) >= 2:
        return parts[0], parts[1].replace(".git", "")
    return owner_input.strip(), repo_input.strip()


async def create_github_issues(
    token: str,
    owner: str,
    repo: str,
    nodes: List[GitHubExportItem]
) -> GitHubExportResponse:
    clean_token = token.strip()
    clean_owner, clean_repo = parse_repo_info(owner, repo)

    headers = {
        "Authorization": f"Bearer {clean_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "TT-TaskTree-App",
    }

    # 1. 대상 저장소 존재 및 권한 확인
    repo_url = f"https://api.github.com/repos/{clean_owner}/{clean_repo}"
    async with httpx.AsyncClient(timeout=20.0) as client:
        check_res = await client.get(repo_url, headers=headers)
        if check_res.status_code == 404:
            raise ValueError(
                f"저장소 '{clean_owner}/{clean_repo}'를 찾을 수 없습니다. "
                "저장소명이 정확한지, Private 저장소라면 토큰에 'repo' 권한이 켜져 있는지 확인하세요."
            )
        elif check_res.status_code == 401:
            raise ValueError("GitHub 토큰 인증 실패 (401 Unauthorized). 올바른 토큰을 입력하세요.")

        # 2. 이슈 생성 진행
        issues_url = f"https://api.github.com/repos/{clean_owner}/{clean_repo}/issues"
        created_urls = []

        for node in nodes:
            issue_title = f"[{node.week}주차 / {node.category.upper()}] {node.title}"

            body_parts = []
            if node.description:
                body_parts.append(f"### 📋 작업 개요\n{node.description}\n")

            if node.tools and len(node.tools) > 0:
                body_parts.append(f"**🛠 추천 도구/스택**: `{', '.join(node.tools)}`\n")

            if node.checklist and len(node.checklist) > 0:
                body_parts.append("### ✅ 체크리스트")
                for chk in node.checklist:
                    body_parts.append(f"- [ ] {chk}")
                body_parts.append("")

            body_parts.append("\n> *Generated by TT (TaskTree) Workflow Canvas*")
            issue_body = "\n".join(body_parts)

            payload = {
                "title": issue_title,
                "body": issue_body,
                "labels": [node.category, f"week-{node.week}"],
            }

            resp = await client.post(issues_url, headers=headers, json=payload)
            if resp.status_code == 201:
                created_urls.append(resp.json().get("html_url"))
            else:
                print(f"[GitHub API Error] {resp.status_code}: {resp.text}")

    return GitHubExportResponse(
        success=len(created_urls) > 0,
        total_created=len(created_urls),
        created_issue_urls=created_urls,
    )